### PR TITLE
New fix bug empty cart at startup

### PR DESCRIPTION
**Pull request by thomascayne**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ok, good to go

**Review by thomascayne — COMMENTED** [review]
I approved

**Comment by thomascayne** [comment]
Closing and going to reopen as this says: https://github.com/orgs/community/discussions/58535?sort=top#discussioncomment-6233887

**Comment by thomascayne** [comment]
Reopening and hopefully it will work

**Comment by ghost** [comment]
Trying to close over here

**Comment by ghost** [comment]
trying again

**Review by ghost — APPROVED** [review]

**Review by thomascayne — COMMENTED** [review]
This should be approved

**Comment by thomascayne** [comment]
close and reopen

**Pull request closed without merging**
